import { StyleSheet } from 'react-native';
import { fontSize, fontWeight, radius, spacing, useAppTheme } from '../../../lib/theme';

export function useHomeDashboardStyles() {
  const { colors } = useAppTheme();

  return StyleSheet.create({
    card: { marginBottom: 0 },
    snapshotRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: 0 },
    snapshotCard: { flex: 1, minHeight: 110, justifyContent: 'space-between' },
    snapshotLabel: { color: colors.textSecondary, fontSize: fontSize.sm, marginBottom: 8 },
    snapshotValue: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: fontWeight.bold },
    balanceCard: { marginBottom: 0 },
    balanceTop: { width: '100%', gap: spacing.xs },
    balanceHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
    balanceLabel: { fontSize: fontSize.sm, color: colors.textSecondary },
    balanceValue: { fontSize: fontSize.xxxl, fontWeight: fontWeight.bold, color: colors.textPrimary, marginBottom: spacing.md },
    savingsPill: { paddingVertical: 6, paddingHorizontal: spacing.sm, borderRadius: radius.full, backgroundColor: colors.surfaceAccentStrong, alignSelf: 'flex-start' },
    savingsText: { fontSize: fontSize.xs, color: colors.accentLight, fontWeight: fontWeight.semibold, textTransform: 'uppercase' },
    negativeBalance: { color: colors.danger },
    balanceDetails: { flexDirection: 'row', width: '100%', paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: `${colors.border}33`, justifyContent: 'space-between' },
    balanceItem: { flex: 1, alignItems: 'flex-start' },
    balanceItemLabel: { fontSize: fontSize.xs, color: colors.textMuted, marginBottom: 2 },
    balanceItemValue: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
    balanceItemDivider: { width: 1, backgroundColor: `${colors.border}33` },
    incomeValue: { color: colors.success },
    expenseValue: { color: colors.danger },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
    cardTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.semibold, color: colors.textPrimary },
    seeAll: { fontSize: fontSize.sm, color: colors.accentLight },
    progressContainer: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.md },
    progressBar: { flex: 1, height: 6, backgroundColor: colors.border, borderRadius: radius.full, overflow: 'hidden' },
    progressFill: { height: '100%', backgroundColor: colors.accent, borderRadius: radius.full },
    progressText: { fontSize: fontSize.xs, color: colors.textSecondary, width: 56 },
    taskList: { gap: spacing.sm },
    taskItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    taskDot: { width: 8, height: 8, borderRadius: radius.full },
    taskContent: { flex: 1 },
    taskTitle: { fontSize: fontSize.sm, color: colors.textPrimary, fontWeight: fontWeight.medium },
    taskDone: { textDecorationLine: 'line-through', color: colors.textMuted },
    taskDeadline: { fontSize: fontSize.xs, color: colors.textMuted, marginTop: 1 },
    emptyText: { color: colors.textSecondary, fontSize: fontSize.sm, textAlign: 'center', paddingVertical: spacing.md },
    quickActions: { flexDirection: 'row', gap: spacing.sm, marginBottom: 0, flexWrap: 'wrap' },
    quickAction: {
      flexBasis: '31%',
      flexGrow: 1,
      backgroundColor: colors.surfaceElevated,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
      minHeight: 116,
      justifyContent: 'center',
      alignItems: 'center',
      gap: spacing.sm,
      shadowColor: colors.shadowDark,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
      elevation: 3,
    },
    quickActionBadge: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
    quickActionIcon: { fontSize: 22 },
    quickActionLabel: { fontSize: fontSize.xs, color: colors.textSecondary, fontWeight: fontWeight.medium, textAlign: 'center' },
    deadlineList: { gap: spacing.sm, marginBottom: 0 },
    deadlineCard: { flexDirection: 'row', alignItems: 'center', padding: spacing.md, backgroundColor: colors.surfaceAccentAlt },
    deadlineContent: { flex: 1 },
    deadlineTaskTitle: { fontSize: fontSize.sm, color: colors.textPrimary, fontWeight: fontWeight.medium },
    deadlineDate: { fontSize: fontSize.xs, color: colors.danger, marginTop: 2 },
    deadlineArrow: { padding: spacing.xs },
    deadlineArrowText: { color: colors.accentLight },
    summaryRow: { flexDirection: 'row', gap: spacing.sm },
    summaryCard: { flex: 1, alignItems: 'center', minHeight: 108, justifyContent: 'center' },
    summaryValue: { fontSize: fontSize.xxxl, fontWeight: fontWeight.bold, color: colors.textPrimary },
    summaryLabel: { fontSize: fontSize.xs, color: colors.textSecondary, marginTop: 2 },
    recentList: { gap: spacing.sm },
    recentRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 42 },
    recentIcon: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
    recentIncome: { backgroundColor: colors.successSoft },
    recentExpense: { backgroundColor: `${colors.rose}22` },
    recentIconText: { color: colors.textPrimary, fontSize: 16, fontWeight: fontWeight.bold },
    recentCopy: { flex: 1, gap: 2 },
    recentTitle: { color: colors.textPrimary, fontSize: fontSize.sm, fontWeight: fontWeight.medium },
    recentMeta: { color: colors.textMuted, fontSize: fontSize.xs },
    recentAmount: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
    insightCard: { gap: spacing.sm, marginBottom: 0 },
    insightHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    insightLabel: { color: colors.accentLight, fontSize: fontSize.xs, fontWeight: fontWeight.semibold, textTransform: 'uppercase' },
    insightTitle: { color: colors.textPrimary, fontSize: fontSize.md, fontWeight: fontWeight.semibold },
    insightBody: { color: colors.textSecondary, fontSize: fontSize.sm, lineHeight: 20 },
  });
}
